#!/bin/bash

mpirun -n 1 -machinefile machinefile_owl7.txt ~/src/quiet/quiet_svn/oslo/src/f90/scalapost/scalapost mask covmat_nside16_70GHz_DX9delta_SS1.unf map2mask_fullsky_n16_nested.fits SS1_70GHzmask_with_planck_prel_polmask_QUonly.fits covmat_nside16_70GHz_DX9delta_SS1_SS1withplanckprelpolmask_QUonly.unf SS1_70GHz_with_planck_prel_polmap2mask_QUonly.fits

mpirun -n 1 -machinefile machinefile_owl7.txt ~/src/quiet/quiet_svn/oslo/src/f90/scalapost/scalapost mask covmat_nside16_70GHz_DX9delta_SS2.unf map2mask_fullsky_n16_nested.fits SS2_70GHzmask_with_planck_prel_polmask_QUonly.fits covmat_nside16_70GHz_DX9delta_SS2_SS2withplanckprelpolmask_QUonly.unf SS2_70GHz_with_planck_prel_polmap2mask_QUonly.fits

mpirun -n 1 -machinefile machinefile_owl7.txt ~/src/quiet/quiet_svn/oslo/src/f90/scalapost/scalapost mask covmat_nside16_70GHz_DX9delta_SS3.unf map2mask_fullsky_n16_nested.fits SS3_70GHzmask_with_planck_prel_polmask_QUonly.fits covmat_nside16_70GHz_DX9delta_SS3_SS3withplanckprelpolmask_QUonly.unf SS3_70GHz_with_planck_prel_polmap2mask_QUonly.fits

mpirun -n 1 -machinefile machinefile_owl7.txt ~/src/quiet/quiet_svn/oslo/src/f90/scalapost/scalapost mask covmat_nside16_70GHz_DX9delta_SS4.unf map2mask_fullsky_n16_nested.fits SS4_70GHzmask_with_planck_prel_polmask_QUonly.fits covmat_nside16_70GHz_DX9delta_SS4_SS4withplanckprelpolmask_QUonly.unf SS4_70GHz_with_planck_prel_polmap2mask_QUonly.fits

mpirun -n 1 -machinefile machinefile_owl7.txt ~/src/quiet/quiet_svn/oslo/src/f90/scalapost/scalapost mask covmat_nside16_70GHz_DX9delta_SS5.unf map2mask_fullsky_n16_nested.fits SS5_70GHzmask_with_planck_prel_polmask_QUonly.fits covmat_nside16_70GHz_DX9delta_SS5_SS5withplanckprelpolmask_QUonly.unf SS5_70GHz_with_planck_prel_polmap2mask_QUonly.fits
